.github/workflows/communitytodevel.yml, .github/workflows/develtomaster.yml, .gitignore, defaults/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/prelim.yml
=> Added GitHub actions and added gitgnore

.github/workflows/communitytodevel.yml, .github/workflows/develtomaster.yml, defaults/main.yml
=> Adjusted GitHub Actions

tasks/fix-cat3.yml
=> Fix typo in SSH_USE_STRONG_RNG

tasks/fix-cat2.yml
* The rhel8stig_login_defaults.umask variable was not being used, so
user customization was not handled
* Fix the regexp on RHEL-08-020351; old version replaced a comment
line and resulted in two UMASK lines in login.defs
* Fix RHEL-08-020352, previous wouldn't match 'umask 027' and wasn't
using the variable.
=> Update umask handling

tasks/fix-cat1.yml, tasks/fix-cat2.yml
Consistent with the RHEL7-STIG syntax.
Some like X11Forwarding would replace comment lines instead of the
desired setting line, leaving duplicate entries.
=> Normalize the regexes on all the sshd_config items

tasks/fix-cat2.yml
The following rules fail a SCAP scan against U_RHEL_8_V1R1_STIG_SCAP_1-2_Benchmark.xml:
* RHEL-08-030000 (missing euid/egid fields, normalized key syntax)
* RHEL-08-030190 (STIG text is /usr/bin/su)
* RHEL-08-030300 (missing /usr/bin/mount rule)
* RHEL-08-030310 (STIG text is /usr/sbin/unix_update)
* RHEL-08-030320 (STIG text is /usr/libexec/...)
* RHEL-08-030490 (missing 32-bit rule)
* RHEL-08-030540 (missing 32-bit rule)
RHEL-08-030121: Need to set in rules.d/audit.rules to persist.
=> Patch audit rules

README.md, defaults/main.yml, handlers/main.yml
Adds a variable to optionally skip rebooting.
Rationale:
When building images with a tool like Packer, the reboot can be disruptive. Packer specifically can deal with this; the issue is FIPS mode. Currently the Go SSH library used in Packer does not use SHA256 fingerprints when authenticating with SSH keys. After the reboot, Packer's SSH connection gets rejected and it can't continue provisioning or even issue the shutdown command if the role is the last provisioning step.
=> Add an option to skip the reboot

tasks/fix-cat2.yml
The ssh private key files should be 0600, not 0640
=> Fix RHEL-08-010490 permissions

defaults/main.yml
Updated the var rhel8stig_local_int_home_file_perms to have 0750 by default instead of 750
- #77 
None
Locally
=> issue #77 fixed

README.md, defaults/main.yml, tasks/main.yml
Attempt to enable end users to be able to run against non supported OSs
#96 
Ability to skip supported OS checks
Manually
=> ability to skip supported os check

handlers/main.yml, tasks/fix-cat2.yml
fapolicy updated to use rules directory and current script configurations will break with the updated fapolicy version. These updates now create the required fapolicy rules in the `rules.d` folder.
https://github.com/ansible-lockdown/RHEL8-STIG/issues/93
Added necessary steps to determine if the `rules.d` directory should be used.
Tested against a CentOS 8 Stream Minimal OS
=> Updated fapolicyd Rules Directory Support - Issue 93 Fix

tasks/fix-cat2.yml
Signed-off-by: Matthew Willis <matthew.willis@outlook.com>
Updated STIG-ID RHEL-08-040111 to blacklist bluetooth kernel module
Fix Text (F-33151r833335_fix)
--
Configure the operating system to disable the Bluetooth adapter when not in use.Build or modify the "/etc/modprobe.d/bluetooth.conf" file with the following line:install bluetooth /bin/trueDisable the ability to use the Bluetooth kernel module.$ sudo vi /etc/modprobe.d/blacklist.confAdd or update the line:blacklist bluetoothReboot the system for the settings to take effect.
```
Configure the operating system to disable the Bluetooth adapter when not in use.
Build or modify the "/etc/modprobe.d/bluetooth.conf" file with the following line:
install bluetooth /bin/true
Disable the …
```
=> Updated STIG-ID RHEL-08-040111 to blacklist bluetooth kernel module

tasks/fix-cat2.yml
**Description of Issue**
The error is when a non elevated account goes into a locked-session, /etc/pam.d/vlock has 
```
#%PAM-1.0
auth    include     system-auth
account required    pam_permit.so
```
in the file, with the permissions of 0640 which is set with remediation tasks (RHEL-08-020101 and RHEL-08-020102). Meaning non-elevated users cannot use vlock to include system-auth since root:root 0640 is applied. When root sessions were locked, there were no issues using vlock to lock/unlock sessions. This only effected non-elevated users.
**Remediation**
I couldn't find it in the RHEL 8 STIG (or anywhere else) if that needed to be 0640 or 0644. As soon as permissions are set to the /etc/pam.d/system-auth to 0644, restart sssd  `systemctl restart sssd` , logged into a new session and …
=> Updated permissions on /etc/pam.d/system-auth to 0644 from 0640.

tasks/fix-cat2.yml
Fix faillog_t permission for faillock dir
The other blocks below seem to be redundant to me, since they seem to do the same in another way
#140
Started wit a system with faillock files with wrong selinux permissins, ran playbook, checked permissions
Logged in with wrong credentials, checked that faillock works and logs the login
Deleted all files in /var/log/faillock
Logged in with wrong credentials, checked that faillock works and logs the login
Manually created a file in /var/log/faillock, checked that faillog_t permissions were given to the new file automatically
=> Fix faillog_t permission for faillock dir

tasks/fix-cat2.yml
Removed permission changes from sshd tasks, including mode, user, and group.
https://github.com/ansible-lockdown/RHEL8-STIG/issues/164
N/A
This has been run against RHEL 8 servers
=> Remove permission changes from sshd tasks

tasks/main.yml
Removed trigger update sysctl task that didn't do anything, since all the sysctl tasks already notify that handler.
https://github.com/ansible-lockdown/RHEL8-STIG/issues/165
N/A
This has been run against RHEL 8 servers
=> Remove trigger update sysctl task

tasks/fix-cat2.yml
This removes permission changes that were in the task for RHEL-08-010295
https://github.com/ansible-lockdown/RHEL8-STIG/issues/166
N/A
This has been run against RHEL 8 servers.
=> RHEL-08-010295 Remove Permission Changes to gnutls.config

tasks/fix-cat2.yml
Moved sssd control conditions so that they are always the first condition. If all sssd controls are disabled, it will now work instead of throwing an error.
https://github.com/ansible-lockdown/RHEL8-STIG/issues/162
N/A
I have tested running this against RHEL 8 servers
=> Move SSSD Control Conditions

tasks/fix-cat2.yml
Correct regex for RHEL-08-010291
#174 
Add single quotes around RHEL-08-040342 regexp and line. 
Run against RHEL 8 server
=> Correct opensshserver.config CRYPTO_POLICY

tasks/fix-cat2.yml
RHEL-08-020011 task currently has an incorrect conditional, `ansible_distribution_version|int >= 8.2` which will evaluate to 8 on a RHEL 8 system, meaning it will never run. This PR corrects this conditional.
N/A
Correcting RHEL-08-020011 conditional
Run on RHEL 8 system
=> Fix RHEL-08-020011 Conditional

tasks/fix-cat2.yml
Fixed the regular expression for finding lines containing the text "kernel.core_pattern" that do not end in /bin/false. Needed to add the -P option to enable look around expressions in grep.
No issue was created
No enhancements, only bug fixes
After running the role, check the file patterns /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf /usr/lib/sysctl.d/*.conf /lib/sysctl.d/*.conf /etc/sysctl.conf /etc/sysctl.d/*.conf for files contain lines containing kernel.core_pattern.
=> Fixed lookbehind regex for rule RHEL-08-010671

tasks/main.yml
Fixed typo in user password assertion
Fixed a typo that I noticed while running this playbook today
None
None
N/A
=> Fixed typo in user password assertion

Changelog.md, handlers/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/fix-cat3.yml, tasks/main.yml, tasks/prelim.yml, vars/is_container.yml
Tidy up and alignment if system_is_container.
- moved priority of the check
- updated container vars
- tidy up of controls now included in vars so control via centralised vars than conditional statements
#204 
thanks to Maheshlagisetti on discord community
Part of #204 tidy up and fqcn of prelim steps
Manually
=> Container updates & issue 204 

ansible.cfg, tasks/fix-cat1.yml, tasks/main.yml, tasks/prelim.yml
Aligned the boot_part variable for FIPs
Improvements for 10020
Manually multiple times with reboot
=> Boot part variable

Changelog.md, tasks/main.yml
Overall Review of Changes:
Improve password check for rule 010380 that sudo user must have a password or sudo will fail to work.
Issue Fixes:
https://github.com/ansible-lockdown/RHEL8-STIG/issues/216
Enhancements:
Only run if the playbook is not being run as a super user
How has this been tested?:
Manually
=> improve password check

tasks/prelim.yml
Changed the when statement for the prelim task to get local home directories to an OR statement for control toggles. This was an issue found via an Automation Counselor client. 
- Incorrect and/or logic in the prelim task to get the list of local home directories fixed
None
Locally
=> Updated when on line 197 of prelim to use an or instead of and

defaults/main.yml
This reverts commit 63c4c8406e7f6b49eeb94d787f258917e8716b0b.
Reversion of a previous commit that introduced a regression.
Fixes #233 
File content verified after running playbook.
=> Revert "fixed gnutls as per issue 196 thansk to @jmalpede"

tasks/fix-cat2.yml
Using `stdout_lines` will ensure that the looped variable is always a list, even with a single entry.
[https://github.com/ansible-lockdown/RHEL8-STIG/issues/261](https://github.com/ansible-lockdown/RHEL8-STIG/issues/261)
Please list any enhancements/features that are not open issue tickets
Mocked scenarios locally
=> Updated RHEL-08-020050 to loop over stdout_lines. Fixes issue #261.

LICENSE, handlers/main.yml, tasks/fix-cat1.yml, tasks/fix-cat2.yml, tasks/fix-cat3.yml, tasks/prelim.yml
Updated relate files for name
License update
file mode updated to symbolic
Manually
=> Name and alignment
