.github/workflows/develtomaster.yml

Fixed master to main

---

.github/workflows/develtomaster.yml

Change master to main in actions

---

defaults/main.yml
tasks/fix-cat2.yml

saw some comments about needing to change `defaults/main.yml` to true, so creating PR for that along with one tag that is set to `rhel_01...` instead of what every other tag is set to `rhel_08...`

updates defaults and fixes typo

---

defaults/main.yml
tasks/fix-cat2.yml

updates defaults and fixes typo

 updates defaults and fixes typo

---

defaults/main.yml
tasks/fix-cat2.yml

April 2021 updates

---

defaults/main.yml
tasks/fix-cat2.yml

Errors in RHEL-08-040123 -> RHEL-08-040134 - logic improved
lint tidy

Fix mount src

---

README.md
defaults/main.yml
handlers/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml

Staging pr 16 through 20

---

README.md
defaults/main.yml
handlers/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/main.yml
tasks/prelim.yml

updates and minor fixes
includes:
- thanks to dcarlojr
- #28 minor bug and typo fixes
- #31 crypto gnu version fix
- thanks cjbidwell
- #29 sssd fixes
- thanks to rx294
- #32 type fix

Updates and fixes

---

defaults/main.yml
tasks/fix-cat2.yml
tasks/prelim.yml
templates/ansible_vars_goss.yml.j2

#40 SSD fixes  
thanks to jsurf
moved to file check only and permissions 0600
other improvements

Sssd v1r2 updates

---

defaults/main.yml
tasks/fix-cat2.yml
tasks/prelim.yml
templates/ansible_vars_goss.yml.j2

Removed old not working statements UID facts and usage
added uid var in template

Stig tweaks

---

defaults/main.yml
tasks/fix-cat2.yml
tasks/prelim.yml
templates/ansible_vars_goss.yml.j2

Add pr39 enhancements pre V1r3
prelim to create faillock dir with selinux context.

Pr 39 enhancements

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
.github/ISSUE_TEMPLATE/question.md
tasks/fix-cat3.yml

Added issue templates

---

.gitattributes

Add attributes file to ensure language displays in github
N/A
N/A
N/A

Added attributes file

---

defaults/main.yml
handlers/main.yml
tasks/fix-cat2.yml

RHEL-08-040137
fapolicy now starts correctly with the added lines
Fixed the variable inheritance to the line in the task and quotes on the defaults lines.
added a handler to restart after changes
#68 
Manually with tags
started and stopped as expected

fapolicy whitelist 040137

---

tasks/prelim.yml

Fix for issue on a prelim task when statement. 
- #72 
n/a
locally

Fix for issue #72

---

README.md

Updated the release version in README
stig v1r4
Please list (using linking) any open issues this PR addresses
Updated to latest fixes in the README file
N/A

 updated with correct stig version

---

tasks/fix-cat2.yml

Updates to controls RHEL-08-040259 and RHEL-08-040260 to correct notify typo
#75 
None
Locally

Fix for issue #75

---

tasks/fix-cat1.yml

Added fix for issue #88 
#88 
None
Locally

Added fix for issue #88

---

tasks/prelim.yml

Updated prelim task for issue #87 
#87 
None
Locally

updated 020027 prelim file task for issue #87

---

tasks/fix-cat3.yml
templates/99-sysctl.conf.j2

Changed the regexp value in the lineinfile module for RHEL-08-010292.
#99  
Please list any enhancements/features that are not open issue tickets
Tested on AMI packer build using Ansible. And scanned with Nessus.

Set SSH_USE_STRONG_RNG. Fix for issue #99

---

tasks/fix-cat2.yml
vars/is_container.yml

Modifications after container testing
none
cleaned up role to run on ubi8-minimal containers
locally with docker

updates for container testing

---

README.md
defaults/main.yml
meta/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml
tasks/prelim.yml

*Release for STIG R1v7*
**summary**
Updates for STIG R1v7
many rule ids changed
text changes in config
no changes to tasks
some lint updates
Manually inline with new audit
updated audit to devel and reran pipeline all success

Stig v1r7 release

---

.github/workflows/github_networks.tf
.github/workflows/github_vars.tfvars
.github/workflows/linux_benchmark_testing.yml
.github/workflows/main.tf
.github/workflows/test.sh
.github/workflows/variables.tf
tasks/main.yml

Added assertion check
Enhance pre testing
Occasionally User passwords are not set and removing NOPASSWD from sudo breaks systems
Manually

Added Assertion for passwd set on ansible user

---

README.md
tasks/fix-cat2.yml
tasks/fix-cat3.yml

Signed-off-by: Bas Meijer <bas.meijer@me.com>
I fixed small typos in the README file and in two tasks files.
Reading English.

Spelling corrections.

---

.github/workflows/linux_benchmark_testing.yml
.yamllint
Makefile
defaults/main.yml
handlers/main.yml
requirements.txt
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml
tasks/main.yml
tasks/parse_etc_passwd.yml
tasks/prelim.yml

Added a `requirements.txt` file to list python libraries
Added a `.yamllint` for a consistent code style and fix these problems in a commit each:
- caeba71 .yamllint file to start refactoring to consistent YAML.
- aa3166a yamllint: document start
- f21b80c yamllint: indentation
- 18f0ccb yamllint: comments-indentation
- a71477e yamllint: truthy value should be one of [false, true] https://github.com/ansible/ansible/issues/78559
**Issues Fixes:**
#115 
#116 
Added a Makefile that runs checks by default.
Makefile added, run `make` or its default target yamllint, or:
```sh
git ls-files "*.yml"|xargs yamllint
```

Fix for #115 and #116

---

.ansible-lint
defaults/main.yml
meta/main.yml
tasks/fix-cat2.yml
tasks/post_remediation_audit.yml
tasks/pre_remediation_audit.yml

Fixed some code style issues that ansible-lint reported. Added exceptions to the skip_list.
#118 
Please list any enhancements/features that are not open issue tickets
Running `ansible-lint` in the role's directory.

ansible-lint fixes

---

defaults/main.yml

Added output file update for audit
Manually

updated audit out file

---

defaults/main.yml
tasks/fix-cat2.yml
tasks/pre_remediation_audit.yml

This covers some updates in early December as well
- #139 
- #142 
- #147 
- #148 
None
locally in Vagrant

Nov 2022 updates

---

defaults/main.yml

Updated to new branch naming for audit
Manually

Update git branch naming convention for audit

---

tasks/fix-cat2.yml

Remove permission changes from tasks that do not have anything to do with file permissions
#175 
N/A
Run against RHEL 8 server

Correct Auditd Permissions

---

.github/workflows/main.tf
Changelog.md
tasks/fix-cat2.yml
tasks/prelim.yml

Based upon #177 
have made and tidied up many related controls.
see changelog
Improved idempotency
manually multiple times

Pamd updates

---

Changelog.md
defaults/main.yml
tasks/fix-cat2.yml

- improvements to openssh configs and separated tasks
Separation of tasks of openssh and greater changes enabled
Manually

Openssh improvements

---

Changelog.md
defaults/main.yml
tasks/fix-cat2.yml

Issues discovered during azure testing
resolved or documented
/var/log check improved
comments around 010600 in defaults regarding azure
also added in fix_cat2
Manually

Mount check improvements

---

tasks/fix-cat1.yml

Add -l option to grep to produce a list of file names instead of a list of matches.
Issue not created
No enhancements, bug fixes only
Executing ansible role with proposed changes runs to completion

Fix rule RHEL-08-040171

---

.github/workflows/update_galaxy.yml
Changelog.md
README.md
defaults/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml
tasks/main.yml
tasks/prelim.yml
templates/ansible_vars_goss.yml.j2
vars/AlmaLinux.yml
vars/OracleLinux.yml
vars/RedHat.yml
vars/Rocky.yml

Stig V1R10 27th April 2023
Audit also updated in branch
- Added new controls
- RHEL-08-10019
- RHEL-08-10358
- updated control IDs
- RHEL-08-10360
- RHEL-08-10540
- RHEL-08-10541
- RHEL-08-10544
- RHEL-08-10800
- RHEL-08-20040
- RHEL-08-20100
- RHEL-08-20101
- RHEL-08-20102
- RHEL-08-20103
- RHEL-08-20220
- RHEL-08-20221
- RHEL-08-20270
- RHEL-08-30070
- RHEL-08-40150
- OracleLinux tested and added
Manually and in pipeline

Stig v1r10 - release

---

defaults/main.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/main.yml
tasks/prelim.yml

Merge April issues into devel
#242 
#251 
#263 
#267 
Some housekeeping and lint
Manually

April 24 issues into devel

---

tasks/fix-cat2.yml

Fix to logic in conditional
#271 
Pipeline

fixed error in conditional rhel-08-020022 #271

---

tasks/fix-cat2.yml

Added ipv6 conditional to 040260 cat 2
manually

updated conditional 040260

---

defaults/main.yml

Issues with historical keys and mere conflicts resolved
Updated from main and merge to devel
rebased to ensure sign off exists
Pipeline

V13 merge fixes

---

tasks/fix-cat2.yml
templates/ansible_vars_goss.yml.j2

Improvements to several tasks
Updates to audit template to improve tests
Manually

May24 updates

---

.github/workflows/devel_pipeline_validation.yml
.github/workflows/main_pipeline_validation.yml
.github/workflows/update_galaxy.yml
Changelog.md
README.md
defaults/main.yml
handlers/main.yml
meta/main.yml
tasks/audit_only.yml
tasks/fix-cat1.yml
tasks/fix-cat2.yml
tasks/fix-cat3.yml
tasks/main.yml
tasks/post_remediation_audit.yml
tasks/pre_remediation_audit.yml
tasks/prelim.yml
vars/audit.yml
vars/main.yml

issues addressed
move to new workflow
audit improvements
#277 
#278 
#289 
Move to new work flow configurations
update to audit config and layout
removal of reliance on jmespath
Manually
bios and efi system
nfs system

issues, workflow and jmespath

---

tasks/fix-cat2.yml

Issue resolved thats to @moncaptain
#312
Manually

fixed 040132-04 issue 312

---

defaults/main.yml
tasks/post_remediation_audit.yml

2025 April Update post audit shell output fix
2025 April Update post audit shell output fix found by JoseLuis
N/A
Pipeline

2025 April Update post audit shell output

---

tasks/LE_audit_setup.yml
tasks/audit_only.yml
tasks/fetch_audit_output.yml
tasks/post_remediation_audit.yml
tasks/pre_remediation_audit.yml
tasks/prelim.yml
tasks/warning_facts.yml
vars/main.yml

Please ensure that you have understood contributing guide
Ensure all commits are signed-by and gpg signed
Update audit functionality
Manually and pipeline

Audit alignment
